config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  resources :bate_papos
  resources :situacoes
  resources :status
  resources :categorias
  resources :chamados
  resources :administradores
  root to: 'rooms#show'

  mount ActionCable.server => '/cable'

  # get "/admin" => redirect("/")
  get '/login', to: 'login#index'
  post '/login/on', to: 'login#login'
  get '/deslogar', to: 'login#logout'

  post '/chamados/:id/alterar', to: 'chamados#alterar'
  post '/chamados/:id/responder', to: 'chamados#responder'

  get '/multiclube', to: 'multiclube#index'
  post '/chamados-multiclube', to: 'chamados_multiclube#create'
  get '/chamados-multiclube', to: 'chamados_multiclube#index'
  get '/chamados-multiclube/novo', to: 'chamados_multiclube#new'
  get '/chamados-multiclube/:id', to: 'chamados_multiclube#show'
  post '/chamados-multiclube/:id/responder', to: 'chamados_multiclube#responder'

end

app/models/administrador.rb
class Administrador < ApplicationRecord
end

app/models/bate_papo.rb
class BatePapo < ApplicationRecord
  belongs_to :usuario
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/chamado.rb
class Chamado < ApplicationRecord
  belongs_to :categoria
  belongs_to :usuario
  belongs_to :situacao

  default_scope { order(updated_at: :desc) }

  attr_accessor :usuario_cpf

  validate :usuario_id, :presence

  before_validation :verifica_usuario_cpf

  def verifica_usuario_cpf
    if self.usuario_cpf.present?
      self.usuario_cpf = self.usuario_cpf.gsub(/\.|-/, '')
      usuarios = Usuario.where(cpf: self.usuario_cpf)
      if usuarios.count > 0
        usuario = usuarios.first
      else
        usuario = Usuario.create(nome: self.usuario_cpf, cpf: self.usuario_cpf)
      end

      self.usuario_id = usuario.id
    end
  end

  def perguntas_respostas
    return @perguntas_respostas if @perguntas_respostas.present?

    @perguntas_respostas = [self]
    carrega_perguntas_respostas(self)
    @perguntas_respostas
  end

  def carrega_perguntas_respostas(chamado)
    chamado = Chamado.where(chamado_id: chamado.id).first
    if chamado.present?
      @perguntas_respostas << chamado
      carrega_perguntas_respostas(chamado)
    end
  rescue;end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/situacao.rb
class Situacao < ApplicationRecord
end

app/models/sql.rb
class Sql
  def self.like
  	ENV['RAILS_ENV'] != "production" ? "like" : "ilike"
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/bate_papos_controller.rb
class BatePaposController < ApplicationController
  before_action :set_bate_papo, only: [:show, :edit, :update, :destroy]

  # GET /bate_papos
  # GET /bate_papos.json
  def index
    @bate_papos = BatePapo.all
    @bate_papo = BatePapo.new
  end

  # GET /bate_papos/1
  # GET /bate_papos/1.json
  def show
  end

  # GET /bate_papos/new
  def new
    @bate_papo = BatePapo.new
  end

  # GET /bate_papos/1/edit
  def edit
  end

  # POST /bate_papos
  # POST /bate_papos.json
  def create
    @bate_papo = BatePapo.new(bate_papo_params)
    @bate_papo.usuario_id = JSON.parse(cookies[:netza_faleconosco])

    if @bate_papo.mensagem.blank?
      redirect_to bate_papos_url
      return
    end

    respond_to do |format|
      if @bate_papo.save
        format.html { redirect_to bate_papos_url, notice: 'Bate papo was successfully created.' }
        format.json { render :show, status: :created, location: @bate_papo }
      else
        format.html { render :new }
        format.json { render json: @bate_papo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bate_papos/1
  # PATCH/PUT /bate_papos/1.json
  def update
    respond_to do |format|
      if @bate_papo.update(bate_papo_params)
        format.html { redirect_to @bate_papo, notice: 'Bate papo was successfully updated.' }
        format.json { render :show, status: :ok, location: @bate_papo }
      else
        format.html { render :edit }
        format.json { render json: @bate_papo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bate_papos/1
  # DELETE /bate_papos/1.json
  def destroy
    @bate_papo.destroy
    respond_to do |format|
      format.html { redirect_to bate_papos_url, notice: 'Bate papo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bate_papo
      @bate_papo = BatePapo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bate_papo_params
      params.require(:bate_papo).permit(:usuario_id, :mensagem)
    end
end

app/helpers/analistas_helper.rb
module AnalistasHelper
end

app/helpers/bate_papos_helper.rb
module BatePaposHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/chamados_helper.rb
module ChamadosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/custos_helper.rb
module CustosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/situacoes_helper.rb
module SituacoesHelper
end

app/helpers/tamanhos_helper.rb
module TamanhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/bate_papos/_form.html.erb
<%= form_for(@bate_papo, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bate_papo.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo</h4>

      <ul>
      <% @bate_papo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :usuario, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :usuario, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mensagem, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :mensagem, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bate_papos/edit.html.erb
<div class="page-header">
  <%= link_to bate_papos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @bate_papo, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando bate_papo</h1>
</div>

<%= render 'form' %>

app/views/bate_papos/index.html.erb
<div class="page-header">
  <%= link_to new_bate_papo_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Bate papo
  <% end %>
  <h1>Listando bate_papos</h1>
</div>

<div style="margin: auto;width: 50%;overflow: scroll;height: 370px;" id="mensagens">
  <% @bate_papos.each do |bate_papo| %>
    <div class="<%= bate_papo.usuario_id == JSON.parse(cookies[:netza_faleconosco]) ? "resposta" : "pergunta" %>">
      <dt><%= bate_papo.usuario.nome%></dt>
      <dd><%= bate_papo.mensagem%></dd>
      <div style="display: flow-root;">
        <dd style="float: right;">
          <%= bate_papo.created_at.strftime("%d/%m/%Y %H:%M")%>
        </dd>
      </div>
    </div>
  <% end %>
</div>
  
<br>

<div style="margin: auto;width: 50%;">
  <br>
  <%= form_for(@bate_papo, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
      <div class="col-sm-10" style="    padding: 0;">
        <%= f.text_field :mensagem, class: "form-control" %>
      </div>
      <div class="col-sm-2">
        <%= f.submit "Enviar", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    var objDiv = document.getElementById("mensagens");
    objDiv.scrollTop = objDiv.scrollHeight;
  });
</script>

app/views/bate_papos/new.html.erb
<div class="page-header">
  <%= link_to bate_papos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo bate_papo</h1>
</div>

<%= render 'form' %>

app/views/bate_papos/show.html.erb
<div class="page-header">
  <%= link_to bate_papos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_bate_papo_path(@bate_papo), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar bate_papo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Usuario:</dt>
  <dd><%= @bate_papo.usuario %></dd>

  <dt>Mensagem:</dt>
  <dd><%= @bate_papo.mensagem %></dd>

</dl>