config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  resources :bate_papos
  resources :situacoes
  resources :status
  resources :categorias
  resources :chamados
  resources :administradores
  root to: 'rooms#show'

  mount ActionCable.server => '/cable'

  # get "/admin" => redirect("/")
  get '/login', to: 'login#index'
  post '/login/on', to: 'login#login'
  get '/deslogar', to: 'login#logout'

  post '/chamados/:id/alterar', to: 'chamados#alterar'
  post '/chamados/:id/responder', to: 'chamados#responder'

  get '/multiclube', to: 'multiclube#index'
  post '/chamados-multiclube', to: 'chamados_multiclube#create'
  get '/chamados-multiclube', to: 'chamados_multiclube#index'
  get '/chamados-multiclube/novo', to: 'chamados_multiclube#new'
  get '/chamados-multiclube/:id', to: 'chamados_multiclube#show'
  post '/chamados-multiclube/:id/responder', to: 'chamados_multiclube#responder'

end

app/models/administrador.rb
class Administrador < ApplicationRecord
end

app/models/bate_papo.rb
class BatePapo < ApplicationRecord
  belongs_to :usuario
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/chamado.rb
class Chamado < ApplicationRecord
  belongs_to :categoria
  belongs_to :usuario
  belongs_to :situacao

  default_scope { order(updated_at: :desc) }

  attr_accessor :usuario_cpf

  validate :usuario_id, :presence

  before_validation :verifica_usuario_cpf

  def verifica_usuario_cpf
    if self.usuario_cpf.present?
      self.usuario_cpf = self.usuario_cpf.gsub(/\.|-/, '')
      usuarios = Usuario.where(cpf: self.usuario_cpf)
      if usuarios.count > 0
        usuario = usuarios.first
      else
        usuario = Usuario.create(nome: self.usuario_cpf, cpf: self.usuario_cpf)
      end

      self.usuario_id = usuario.id
    end
  end

  def perguntas_respostas
    return @perguntas_respostas if @perguntas_respostas.present?

    @perguntas_respostas = [self]
    carrega_perguntas_respostas(self)
    @perguntas_respostas
  end

  def carrega_perguntas_respostas(chamado)
    chamado = Chamado.where(chamado_id: chamado.id).first
    if chamado.present?
      @perguntas_respostas << chamado
      carrega_perguntas_respostas(chamado)
    end
  rescue;end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/situacao.rb
class Situacao < ApplicationRecord
end

app/models/sql.rb
class Sql
  def self.like
  	ENV['RAILS_ENV'] != "production" ? "like" : "ilike"
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to @categoria, notice: 'Categoria foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to @categoria, notice: 'Categoria foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to categorias_url, notice: 'Categoria foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:nome)
    end
end

app/helpers/analistas_helper.rb
module AnalistasHelper
end

app/helpers/bate_papos_helper.rb
module BatePaposHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/chamados_helper.rb
module ChamadosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/custos_helper.rb
module CustosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/situacoes_helper.rb
module SituacoesHelper
end

app/helpers/tamanhos_helper.rb
module TamanhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/categorias/_form.html.erb
<%= form_for(@categoria, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @categoria.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo</h4>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categorias/edit.html.erb
<div class="page-header">
  <%= link_to categorias_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @categoria, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando categoria</h1>
</div>

<%= render 'form' %>

app/views/categorias/index.html.erb
<div class="page-header">
  <%= link_to new_categoria_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Categoria
  <% end %>
  <h1>Listando categorias</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @categorias) do |categoria| %>
        <td><%= categoria.nome %></td>
        <td><%= link_to 'Mostrar', categoria %></td>
        <td><%= link_to 'Editar', edit_categoria_path(categoria) %></td>
        <td><%= link_to 'Apagar', categoria, method: :delete, data: { confirm: 'Tem certeza ?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categorias/new.html.erb
<div class="page-header">
  <%= link_to categorias_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo categoria</h1>
</div>

<%= render 'form' %>

app/views/categorias/show.html.erb
<div class="page-header">
  <%= link_to categorias_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_categoria_path(@categoria), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar categoria</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @categoria.nome %></dd>

</dl>