config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  resources :bate_papos
  resources :situacoes
  resources :status
  resources :categorias
  resources :chamados
  resources :administradores
  root to: 'rooms#show'

  mount ActionCable.server => '/cable'

  # get "/admin" => redirect("/")
  get '/login', to: 'login#index'
  post '/login/on', to: 'login#login'
  get '/deslogar', to: 'login#logout'

  post '/chamados/:id/alterar', to: 'chamados#alterar'
  post '/chamados/:id/responder', to: 'chamados#responder'

  get '/multiclube', to: 'multiclube#index'
  post '/chamados-multiclube', to: 'chamados_multiclube#create'
  get '/chamados-multiclube', to: 'chamados_multiclube#index'
  get '/chamados-multiclube/novo', to: 'chamados_multiclube#new'
  get '/chamados-multiclube/:id', to: 'chamados_multiclube#show'
  post '/chamados-multiclube/:id/responder', to: 'chamados_multiclube#responder'

end

app/models/administrador.rb
class Administrador < ApplicationRecord
end

app/models/bate_papo.rb
class BatePapo < ApplicationRecord
  belongs_to :usuario
end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/chamado.rb
class Chamado < ApplicationRecord
  belongs_to :categoria
  belongs_to :usuario
  belongs_to :situacao

  default_scope { order(updated_at: :desc) }

  attr_accessor :usuario_cpf

  validate :usuario_id, :presence

  before_validation :verifica_usuario_cpf

  def verifica_usuario_cpf
    if self.usuario_cpf.present?
      self.usuario_cpf = self.usuario_cpf.gsub(/\.|-/, '')
      usuarios = Usuario.where(cpf: self.usuario_cpf)
      if usuarios.count > 0
        usuario = usuarios.first
      else
        usuario = Usuario.create(nome: self.usuario_cpf, cpf: self.usuario_cpf)
      end

      self.usuario_id = usuario.id
    end
  end

  def perguntas_respostas
    return @perguntas_respostas if @perguntas_respostas.present?

    @perguntas_respostas = [self]
    carrega_perguntas_respostas(self)
    @perguntas_respostas
  end

  def carrega_perguntas_respostas(chamado)
    chamado = Chamado.where(chamado_id: chamado.id).first
    if chamado.present?
      @perguntas_respostas << chamado
      carrega_perguntas_respostas(chamado)
    end
  rescue;end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/situacao.rb
class Situacao < ApplicationRecord
end

app/models/sql.rb
class Sql
  def self.like
  	ENV['RAILS_ENV'] != "production" ? "like" : "ilike"
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/chamados_controller.rb
class ChamadosController < ApplicationController
  before_action :set_chamado, only: [:show, :edit, :update, :destroy, :responder, :alterar]

  # GET /chamados
  # GET /chamados.json
  def index
    @chamados = Chamado.where("chamado_id is null")
    options = {page: params[:page] || 1, per_page: 10}
    if params[:busca].present?

      if params[:busca][:usuario].present?
        @chamados = @chamados.where("usuario_id in ( select usuarios.id from usuarios where usuarios.nome #{Sql.like} '%#{params[:busca][:usuario]}%' )")
      end

      if params[:busca][:assunto].present?
        @chamados = @chamados.where("assunto #{Sql.like} '%#{params[:busca][:assunto]}%' ")
      end

      if params[:busca][:categoria_id].present?
        @chamados = @chamados.where("categoria_id = #{params[:busca][:categoria_id]} ")
      end

      if params[:busca][:situacao_id].present?
        @chamados = @chamados.where("situacao_id = #{params[:busca][:situacao_id]} ")
      end
    end

    @chamados = @chamados.paginate(options)
  end

  # GET /chamados/1
  # GET /chamados/1.json
  def show
    @chamado.lido = true
    @chamado.save
  end

  # GET /chamados/new
  def new
    @chamado = Chamado.new
  end

  # GET /chamados/1/edit
  def edit
  end

  def alterar
    @chamado.situacao_id = params[:resposta][:situacao_id]
    @chamado.save!

    redirect_to "/chamados/#{@chamado.id}"
  end

  def responder
    situacao = Situacao.where(nome: "Suporte respondeu").first

    chamado_original = Chamado.find(params[:chamado_original_id])
    chamado_original.situacao_id = situacao.id
    chamado_original.lido_usuario = false
    chamado_original.save

    resposta = Chamado.new
    resposta.administrador_id = administrador.id
    resposta.chamado_id = @chamado.id
    resposta.categoria_id = chamado_original.categoria_id
    resposta.assunto = chamado_original.assunto
    resposta.comentario = params[:resposta][:comentario]
    resposta.usuario_id = chamado_original.usuario_id
    resposta.situacao_id = situacao.id
    resposta.save!

    redirect_to "/chamados/#{chamado_original.id}"
  end

  # POST /chamados
  # POST /chamados.json
  def create
    @chamado = Chamado.new(chamado_params)

    respond_to do |format|
      if @chamado.save
        format.html { redirect_to @chamado, notice: 'Chamado foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @chamado }
      else
        format.html { render :new }
        format.json { render json: @chamado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chamados/1
  # PATCH/PUT /chamados/1.json
  def update
    respond_to do |format|
      if @chamado.update(chamado_params)
        format.html { redirect_to @chamado, notice: 'Chamado foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @chamado }
      else
        format.html { render :edit }
        format.json { render json: @chamado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chamados/1
  # DELETE /chamados/1.json
  def destroy
    @chamado.destroy
    respond_to do |format|
      format.html { redirect_to chamados_url, notice: 'Chamado foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chamado
      @chamado = Chamado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chamado_params
      params.require(:chamado).permit(:categoria_id, :assunto, :comentario, :usuario_id, :administrador_id, :status, :lido, :chamado_id, :usuario_cpf, :situacao_id)
    end
end

app/helpers/analistas_helper.rb
module AnalistasHelper
end

app/helpers/bate_papos_helper.rb
module BatePaposHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/chamados_helper.rb
module ChamadosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/custos_helper.rb
module CustosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/situacoes_helper.rb
module SituacoesHelper
end

app/helpers/tamanhos_helper.rb
module TamanhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/chamados/_form.html.erb
<%= form_for(@chamado, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @chamado.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo</h4>

      <ul>
      <% @chamado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :categoria_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :categoria_id, Categoria.all.collect { |categoria| [categoria.nome, categoria.id] }, :selected => @chamado.categoria_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :situacao_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :situacao_id, Situacao.all.collect { |situacao| [situacao.nome, situacao.id] }, :selected => @chamado.situacao_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :assunto, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :assunto, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comentario, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :comentario, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :usuario_cpf, "CPF Usuario", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :usuario_cpf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/chamados/edit.html.erb
<div class="page-header">
  <%= link_to chamados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @chamado, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando chamado</h1>
</div>

<%= render 'form' %>

app/views/chamados/index.html.erb
<div class="page-header">
  <%= link_to new_chamado_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Chamado
  <% end %>
  <h1>Listando chamados</h1>
</div>

<%= form_for(:busca, url: "/chamados", html: { method: "GET", class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.label :usuario, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :usuario, value: (params[:busca][:usuario] rescue nil), class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :assunto, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :assunto, value: (params[:busca][:assunto] rescue nil), class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :categoria_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :categoria_id, Categoria.all.collect { |categoria| [categoria.nome, categoria.id] }, class: "form-control", :selected => (params[:busca][:categoria_id] rescue nil), :include_blank => "[Selecione]" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :situacao_id, "Situação", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :situacao_id, Situacao.all.collect { |situacao| [situacao.nome, situacao.id] }, :include_blank => "[Selecione]", :selected => (params[:busca][:situacao_id] rescue nil), class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Buscar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<hr>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Número</th>
        <th>Categoria</th>
        <th>Assunto</th>
        <th>Usuario</th>
        <th>Data</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @chamados.each do |chamado| %>
      <tr class="<% unless chamado.lido %> bold <% end %>">
        <td><%= chamado.id %></td>
        <td><%= chamado.categoria.nome %></td>
        <td><%= chamado.assunto %></td>
        <td><a href="/usuarios/<%= chamado.usuario.id %>"><%= chamado.usuario.nome %></a></td>
        <td><%= chamado.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td style="background-color:<%= chamado.situacao.cor %>"><%= chamado.situacao.nome %></td>
        <td><%= link_to 'Responder', chamado %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="apple_pagination">
  <%= will_paginate @alunos, :container => false %>
</div>

app/views/chamados/new.html.erb
<div class="page-header">
  <%= link_to chamados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo chamado</h1>
</div>

<%= render 'form' %>

app/views/chamados/show.html.erb
<div class="page-header">
  <%= link_to chamados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_chamado_path(@chamado), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar chamado</h1>
</div>

<dl class="dl-horizontal">
  <dt>Categoria:</dt>
  <dd><%= @chamado.categoria.nome %></dd>

  <dt>Assunto:</dt>
  <dd><%= @chamado.assunto %></dd>

  <dt>Usuario:</dt>
  <dd><%= @chamado.usuario.nome %></dd>

  <dt>Status:</dt>
  <dd>
    <div style="width: 200px;background-color:<%= @chamado.situacao.cor %>; padding: 10px; border-radius: 6px;text-align: center;">    
    <%= @chamado.situacao.nome %>
    </div>    
  </dd>

  <dt>Lido:</dt>
  <dd><%= @chamado.lido ? "Sim" : "Não" %></dd>
</dl>
<hr>
<%= form_for(:resposta, url: "/chamados/#{@chamado.id}/alterar", html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @chamado.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo</h4>

      <ul>
      <% @chamado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :situacao_id, "Situação", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.select :situacao_id, Situacao.all.collect { |situacao| [situacao.nome, situacao.id] }, :selected => @chamado.situacao_id, class: "form-control" %>
    </div>
    <div class="col-sm-8">
      <%= f.submit "Alterar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<hr>
<% @chamado.perguntas_respostas.each do |pr| %>
<div class="<%= pr.administrador_id.present? ? "resposta" : "pergunta" %>">
  <dt><%= pr.administrador_id.present? ? "Resposta" : "Pergunta" %>:</dt>
  <dd><%= pr.comentario %></dd>
  <dd><%= pr.created_at.strftime("%d/%m/%Y %H:%M") %></dd>
</div>
<% end %>
<hr>zz
<%= form_for(:resposta, url: "/chamados/#{@chamado.perguntas_respostas.last.id}/responder", html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <input type="hidden" name="chamado_original_id" value="<%= @chamado.id %>">
    <%= f.label :comentario, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :comentario, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Responder", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>